services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    networks:
      - socket_proxy
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      REDIS_HOST: nc-redis
      NEXTCLOUD_TRUSTED_DOMAIN: nextcloud.$DOMAINNAME_1
      TRUSTED_PROXIES: 192.168.90.0/24,192.168.91.0/24
    volumes:
     # - $DOCKERDIR/appdata/nextcloud:/var/www/html
      - $DOCKERDIR/appdata/nextcloud/data:/data
     # - $DOCKERDIR/appdata/nextcloud/config:/var/www/html/config
    #ports:
    #  - 443:443
    secrets:
      - db_password
      - db_root_password
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.nextcloud-rtr.entrypoints=websecure"
      - "traefik.http.routers.nextcloud-rtr.rule=Host(`nextcloud.$DOMAINNAME_1`)"
      - "traefik.http.routers.nextcloud-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.nextcloud-rtr.middlewares=chain-no-auth@file" 
      ## HTTP Services
      - "traefik.http.routers.nextcloud-rtr.service=nextcloud-svc"
      - "traefik.http.services.nextcloud-svc.loadbalancer.server.port=80"